name: chronotrack
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  http: ^1.2.1
  excel: ^2.1.0
  amplify_flutter: ^2.6.1
  amplify_auth_cognito: ^2.6.1
  amplify_authenticator: ^2.2.0       # ✅ Dart 3.4-compatible
  jwt_decoder: ^2.0.1
  intl: ^0.20.2
  amplify_api: ^2.1.0
  url_launcher: ^6.2.5
  mime: ^1.0.4
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/default-icon.png      # ✅ Corrected the typo: "assests" → "assets"
